[package]
name = "modern-g7-32"
version = "0.1.0"
entrypoint = "src/export.typ"
authors = ["Forgenet"]
license = "MIT"
description = "GOST 7.32-2017 template"
repository = "https://github.com/typst-g7-32/modern-g7-32"
keywords = ["gost", "7.32", "2017", "science"]
categories = ["cv"]
exclude = [
	".github",
	"docs",
	"tests",
	".typstignore",
]

[template]
path = "template"
entrypoint = "main.typ"